# Site Variables
title: Frootlab
subtitle: Smart Analytics
description: Frootlab Smart Analytics Homepage and Corporate Blog
url: https://www.frootlab.org
relation: https://frootlab.github.io
logo: frootlab.png
locale: en_US
language: en
copyright: © 2019 Frootlab
keywords:
  Frootlab, Smart Analytics, Cloud-Assisted Meta Programming, CAMP,
  Liquid Coding, Nemoa, Pandora, Motley, flib, Machine Learning
future: true

# Left Block Images
background:
  homepage: images/back/home.webp
  post-list: images/back/painting.webp
  default-post: images/back/painting.webp
  default-author: images/back/robot.webp

# Collections
collections:
  authors:
    output: true

# Jekyll
#permalink:          /:title/
markdown:           kramdown
remote_theme:       taylantatli/Halve
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics: UA-136312456-1

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
