# Site
title: Frootlab
description: Smart Analytics
url: https://www.frootlab.org
logo: frootlab.png
locale: en_US
future: true

# Left Block Images
background:
  homepage: images/back/home.webp
  post-list: images/back/news.webp
  default-post: images/back/news.webp

# Jekyll
#permalink:          /:title/
markdown:           kramdown
remote_theme:       taylantatli/Halve
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics: UA-136312456-1

# Social Links
email:              contact@frootlab.org
#google.plus:        username
#twitter:            username
#facebook:           username
github:             frootlab
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
xmpp:               fishroot@wiuwiu.de
#hackernews:        username
#behance:           username

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
