# Site Variables
title: Frootlab
subtitle: Smart Analytics
description: Frootlab Smart Analytics Homepage and Corporate Blog
url: https://www.frootlab.org
relation: https://frootlab.github.io
logo: frootlab.png
locale: en_US
language: en
copyright: © 2019 Frootlab
keywords:
  Frootlab, Smart Analytics, Machine Learning, AutoML, AI, Liquid Code, Nemoa,
  Pandora, Motley, flib, Cloud-Assisted Meta Programming, CAMP
future: true

# Left Block Images
background:
  default: images/default.webp

# Collections
collections:
  authors:
    output: true
  projects:
    output: true
  news:
    output: true
    permalink: /microblog/:year/:month/:slug/

# Jekyll
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         _sass
  style:            compressed

# Google Analytics
google-analytics: UA-136312456-1

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

# Jekyll-Feed Settings
# see: https://github.com/jekyll/jekyll-feed
feed:
  categories:
    - corporate
    - science
  collections:
    - news

# HTML Compression
# see: https://github.com/penibelst/jekyll-compress-html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]

# Front Matter Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      sections: false
      license: "CC BY 4.0"
      license-url: "https://creativecommons.org/licenses/by/4.0/"
      navid: "blog"
  -
    scope:
      path: ""
      type: "news"
    values:
      layout: "micropost"
      sections: false
      license: "CC0 1.0"
      license-url: "https://creativecommons.org/publicdomain/zero/1.0/"
      navid: "microblog"
      image-meta:
        cloudinary: pexels/323645
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      sections: true
      backdrop: "white"
      layout: "project"
      navid: "projects"
      license: "GPL-3.0"
      license-url: "https://www.gnu.org/licenses/gpl-3.0"
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      sections: true
      backdrop: "white"
